name: Deploy to Netlify

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Déploiement
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@v2.0.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: 53032d03-f184-45a8-a5a7-c412ba1e645c
          DIR: '/'
